name = "bg-rendezvous"
main = "src/worker.js"
compatibility_date = "2026-02-08"
workers_dev = true

[[durable_objects.bindings]]
name = "RENDEZVOUS"
class_name = "RendezvousRoom"

[[durable_objects.bindings]]
name = "ROOM_DIRECTORY"
class_name = "RoomDirectory"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RendezvousRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["RoomDirectory"]
